Repository ondrys123/wuss, pull requests merged in 2021-04, with the labels that each got.

#16 Added missing ecalls
  misc/enclave.edl
  trusted/ecalls.cpp
  trusted/wallet.cpp
  trusted/wallet.hpp
Labels: enhancement

#17 Added set of items and masster password
  trusted/item.hpp
  trusted/wallet.cpp
  trusted/wallet.hpp
Labels: enhancement

#19 Implement wallet methods
  .clang-format
  misc/enclave.edl
  trusted/ecalls.cpp
  trusted/wallet.cpp
  trusted/wallet.hpp
  untrusted/enclave_wrapper.cpp
  untrusted/enclave_wrapper.hpp
  untrusted/io_handler.cpp
Labels: enhancement

#22 Store
  misc/enclave.edl
  trusted/storage_handler.cpp
  trusted/storage_handler.hpp
  trusted/wallet.cpp
  trusted/wallet.hpp
  untrusted/enclave_wrapper.cpp
  untrusted/enclave_wrapper.hpp
  untrusted/ocalls.cpp
Labels: enhancement

#23 Finish io handler
  untrusted/io_handler.cpp
  untrusted/io_handler.hpp
Labels: enhancement

#27 Bugfixes
  CMakeLists.txt
  trusted/wallet.cpp
Labels: bug

#26 add password policy check
  trusted/wallet.cpp
  trusted/wallet.hpp
  untrusted/io_handler.cpp
Labels: enhancement

#30 Add password generation
  misc/enclave.edl
  trusted/ecalls.cpp
  trusted/pswd_params.hpp
  trusted/wallet.cpp
  trusted/wallet.hpp
  untrusted/enclave_wrapper.cpp
  untrusted/enclave_wrapper.hpp
  untrusted/io_handler.cpp
  untrusted/io_handler.hpp
Labels: enhancement

#34 Add master password hashing
  trusted/wallet.cpp
Labels: non essential
